name: Veracode_Basic

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Empacotar e Publicar Artefato
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Empacotamento dos arquivos
        uses: thedoctor0/zip-release@master
        with:
          filename: 'veracode.zip'
          path: .

      - name: Publicando Artefato
        uses: actions/upload-artifact@v4
        with:
          name: pacoteVeracode
          path: veracode.zip

  veracode_scan:
    name: Upload e Análise Veracode
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download do Artefato
        uses: actions/download-artifact@v4
        with:
          name: pacoteVeracode

      - name: Upload e Scan com Veracode
        uses: veracode/veracode-uploadandscan-action@master
        with:
          vid: '${{ secrets.VeracodeID }}'
          vkey: '${{ secrets.VeracodeKey }}'
          appname: 'Github Actions - ${{ github.repository }}'
          createsandbox: true
          filepath: 'veracode.zip'
          deleteIncompleteScan: false
          version: '${{ github.run_id }}'
          criticality: 'VeryHigh'
